/** Portfolio-safe display names (no employer-specific terminology). */

export const LEX = {
  appTitle: "Delivery Operations",
  companyName: "Synthetic Delivery Network",
  companyBlurb: "Fictional delivery network — all metrics are simulated.",
  appSubtitle: "Sign in to access the analytics workspace",
  warehouseSignIn: "Initialize demo data",
  warehouseSigningIn: "Initializing…",
  warehouseTitle: "Initialize the bundled synthetic data",
  warehouseRefreshHint: "Regenerate the cached fictional metrics",
  warehouseRefreshNote: "All refreshed values are generated locally.",

  tabRegion: "Network",
  tabMarket: "Market",
  tabSla: "SLA breaches",
  tabQueue: "Queue aging",
  tabRedispatch: "Redispatch",
  tabAccept: "Accept latency",
  tabLogs: "Logs",

  demoDisclaimer: "Synthetic Delivery Network demo · all figures are simulated for portfolio use.",

  metrics: {
    totalOrders: "Completed jobs",
    slaBreach: "SLA breach share",
    slaBreachShort: "Breach %",
    queueAging: "Queue aging share",
    queueAgingShort: "Aging %",
    oversizeABreach: "Tier A breach share",
    oversizeAShort: "Tier A %",
    oversizeBBreach: "Tier B breach share",
    oversizeBShort: "Tier B %",
    redispatch: "Redispatch share",
    redispatchShort: "Redispatch %",
    cycleTime: "Mean cycle time",
    cycleTimeShort: "Cycle",
    acceptLatency: "Mean accept latency",
    acceptLatencyShort: "Accept",
    acceptLatencySec: "Accept (s)",
    breachCount: "SLA breach count",
    breachRate: "Breach rate",
    agingCount: "Queue aging count",
    agingRate: "Aging rate",
    officialBreach: "Audited breach count",
    reasonHeading: "Root-cause signals (multi-tag)",
    slaTrend: "SLA breach trend",
    agingTrend: "Queue aging trend",
    oversizeA: "Tier A (oversize)",
    oversizeB: "Tier B (oversize)",
    oversizeBoth: "Tier A | B",
    partner: "Partner",
    fieldUnit: "Field unit",
  },
} as const;
